### PR TITLE
Merge main article to master branch.  Cloned NY times webpage using HTML and CSS.

### PR DESCRIPTION
**Pull request by Meltrust**
Submission for review.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!

### Good job this far, however, you have changes you need to work on before your project could be approved.
- Your reset.css file is overriding your main.css styles. Change the order
css
- This is how it looks.
page
- Write a more descriptive pull request [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- Make this change and resubmit for another code review.

**Comment by Meltrust** [comment]
> Hello Team!
> ### Good job this far, however, you have changes you need to work on before your project could be approved.
> 
>     * Your reset.css file is overriding your main.css styles. Change the order
>       css
> 
>     * This is how it looks.
>       page
> 
>     * Write a more descriptive pull request [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> 
>     * Make this change and resubmit for another code review.

Done! Thanks!

**Comment by davidmrtz-dev** [comment]
Pull Request under the review by David E. (TSE)

**Comment by davidmrtz-dev** [comment]
### Status: Changes required.

Hi @Meltrust !
**Very good work! You have done a very good job so far.
There's only one change you need to work on before your project could be approved.**

**Footer**

- [x] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

Remember, this project consists of making a clone. Keep eyes on the details. 👀 😄 

**[OPTIONAL]**

- [x] You cand improve your README file to show your Github user instead of the raw link.

Here's an image!

Screen Shot 2020-02-18 at 8 53 06 PM

You can use something like:

> ## Authors
> 
> 👤 **Your name here**
> 
> - Github: [@yuoruser](https://github.com/youruser)
> - Linkedin: [linkedin](https://linkedin.com/youruser)

**Happy Coding! 💻** 

- Make this change and resubmit for another code review. 💯 

David. 👨‍💻 
[@davitomix](https://github.com/davitomix)

**Comment by Meltrust** [comment]
> ### Status: Changes required.
> 
> Hi @Meltrust !
> **Very good work! You have done a very good job so far. There's only one change you need to work on before your project could be approved.**
> 
> **Footer**
> 
>     * [x]  It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
> 
> 
> Remember, this project consists of making a clone. Keep eyes on the details. eyes smile
> 
> **[OPTIONAL]**
> 
>     * [x]  You cand improve your README file to show your Github user instead of the raw link.
> 
> 
> Here's an image!
> 
> Screen Shot 2020-02-18 at 8 53 06 PM
> 
> You can use something like:
> 
> > ## Authors
> > bust_in_silhouette **Your name here**
> > 
> > * Github: [@yuoruser](https://github.com/youruser)
> > * Linkedin: [linkedin](https://linkedin.com/youruser)
> 
> **Happy Coding! computer**
> 
>     * Make this change and resubmit for another code review. 100
> 
> 
> David. man_technologist
> [@davitomix](https://github.com/davitomix)

Done! Ty!

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Comment by kobiyoyo** [comment]
## Hi @Meltrust       
#### Great Job so far, but there is one more thing to do. 
### General
- [ ] The whole page isn't positioned well, maybe due to a CSS file not rendering well,Lets fix that.
Screenshot from 2020-02-19 06-08-28

### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Meltrust       
#### Great Job so far, but there is one more thing to do. 
### General
- [ ] The whole page isn't positioned well, maybe due to a CSS file not rendering well,Lets fix that.
Screenshot from 2020-02-19 06-08-28

### Make changes and submit another code review request.
*Happy coding*

**Comment by davidmrtz-dev** [comment]
Pull Request under review by  **[TSE] David Elí**. 👨‍💻

**Comment by davidmrtz-dev** [comment]
# **Status: Changes required.** ♻️  
Hi @Meltrust . 😄 🌟 

**Very nice work on this project, however, the following issues need to be fixed before moving on.** ⬇️ 

## Footer
- [x] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)).

Here I show how the footer should look: 

Screen Shot 2020-02-19 at 1 13 43 AM

As you can see the footer stays fixed at the bottom of the page.

I'll recommend you to add to the main footer class the property to stay fixed.

`footer {`
`	position: fixed;`
`} `

Please make changes required and submit a new TSE revision. 🙏 


**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by lekegitrepo** [comment]
Pull Request under review by **[TSE] Temitayo Adeleke**

**Comment by lekegitrepo** [comment]
**Hi @Meltrust, :+1:**
You have done a lot of work and the page is looking great now. Base on the previous reviews and the last required correction('It should have a fixed position (**it sticks to the bottom part of the screen)**) I'm approving this project. So good luck with your next project.

Reviewed by: Temitayo Adeleke
-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]

**Pull request merged**
